### ISSUE TITLE
Run piranha on a single GPU machine with multiple GPUs

### ISSUE THREAD

**Issue by DylanWangWQF** [ucbrise/piranha#1]
Hi Jean-Luc @jlwatson ,
  As introduced, piranha runs on 2/3/4 machines in the AWS cluster.
  However,  currently, I have only one GPU machine with 4 Tesla GPUs or some GPU machines with different hardware configurations.
  Does piranha provide a simulation for running it on a single GPU machine with multiple GPUs？
  Thanks in advance!

**Comment by jlwatson** [comment]
Hey, great question! I do have a slightly janky setup for running the code on a single machine with multiple GPUs that I'll clean up and push in the next day or so. It'll let you set which GPU to run each party on -- I'll include some instructions too :)

**Comment by DylanWangWQF** [comment]
Looking forward to this nice update!  I believe this is what some people expect.

**Comment by jlwatson** [comment]
[#8fd8219](https://github.com/ucbrise/piranha/commit/8fd8219a8cf2f6d15fc5d0777310cdc87ffd9e8c) should address this; README updated to give some clear instructions for running on localhost. You can modify which GPUs without code changes by limiting which GPU each process sees using `CUDA_VISIBLE_DEVICES`.

Feel free to PR if you run into any issues and the instructions need an update :)
